# Site settings
baseurl = "http://blog.dyngr.com/"
languageCode = "en-us"
title = "Never More: a personal site of Ye Ding"
theme = "hugo-redlounge"
paginate = 8
paginatePath = "page"
googleAnalytics = "UA-42770963-1"
disqusShortname = "dyngblog"
enableEmoji = true
hasCJKLanguage = true
footnotereturnlinkcontents = "↩"

[permalinks]
    blog = "/blog/:year/:month/:day/:filename"

[params]

    # Sidebar
    sidebartitle = "Never More"
    sidebartagline = "自然体，平常心"
    sidebarbackground = "/images/cover.jpg"

    # Custom Css
    categoriescss = "/assets/css/categories.css"

    # Sections
    [[menu.main]]
        name = "About"
        url = "/about"

    # Social
    [[menu.social]]
        pre = "<i class='fa fa-github'></i>"
        url = "https://github.com/dyng"
        identifier = "github"

    [[menu.social]]
        pre = "<i class='fa fa-twitter'></i>"
        url = "https://twitter.com/gbingdu"
        identifier = "twitter"

    [[menu.social]]
        pre = "<i class='fa fa-weibo'></i>"
        url = "http://weibo.com/dyngrr"
        identifier = "weibo"
